### ISSUE TITLE
warning about importing the future

### ISSUE THREAD

**Issue by rnuske** [chdemko/pandoc-latex-unlisted#3]
Thanks a lot for this filter it works perfectly. I am using it in a `bookdown` project. 

The only thing worrying me is the warning that is displayed every time I convert a markdown file to PDF with pandoc. `click` complains about `unicode_literals __future__ import`. 
Is something wrong with my setup? Am I using the wrong Python version?

The behavior is reproducible with your example on ubuntu 18.04 and pandoc 2.3.1 (brought in by RStudio):
```
pandoc -N pandoc-latex-unlisted-sample.txt --pdf-engine=xelatex --filter pandoc-latex-unlisted -o out.pdf
```
results in exactly the pdf shown in your wiki and the following warning
```
/usr/local/lib/python2.7/dist-packages/panflute/autofilter.py:163: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see https://click.palletsprojects.com/python3/
  "that is appended to the search list.")
```

**Comment by chdemko** [comment]
This issue is due to the panflute python package which is used by pandoc-latex-unlisted. Generally speaking, this kind of "error" is due to the use of an old python version (in your case 2.7) which will die in 10 months... https://pythonclock.org/

**Comment by rnuske** [comment]
ubuntu 18.04 comes with an old (2.7.15) and new (3.6.7) python. By default `python` calls the old and `python3` the new python.

Do you know how to make `pandoc-latex-unlisted` use the newer python without changing the default python?

Thanks again for the great filter!

**Comment by chdemko** [comment]
try to install `pandoc-latex-unlisted` with python3:

~~~console
$ python3 -m pip install pandoc-latex-unlisted
~~~

This should install `pandoc-latex-unlisted` with python3. If it does not work uninstall and reinstall it with this command.

**Comment by rnuske** [comment]
Fantastic 🎉
This works like a treat. Thanks a ton!
